### ISSUE TITLE
Calculate transform matrices at compile-time

### ISSUE THREAD

**Issue by FreezyLemon** [rust-av/yuvxyb#24]
`src/yuv_rgb/color.rs` has quite a bit of code that can logically be const-evaluated.

Basically, `get_rgb_to_yuv_matrix` and `get_yuv_to_rgb_matrix` (which is the first function plus 1 step) can be simplified into lookups of 3x3 matrices based only on the `MatrixCoefficients` and `ColorPrimaries`.

This could either be done by moving the calculation code into a build script (similar to [this PR](https://github.com/rust-av/ssimulacra2/pull/17) in ssimulacra2), or by using soft floats (e.g. [const_soft_float](https://crates.io/crates/const_soft_float) and/or [constgebra](https://crates.io/crates/constgebra)).

This could also allow removing the `nalgebra` dependency, since the only `nalgebra` code that really needs to run at runtime is the `pix_vector * transform_matrix` multiplication, which can be ported to a trivial helper function (because the dimensions are always the same).

**Comment by FreezyLemon** [comment]
I've played around with this a bit and it looks like this won't be a real performance increase, maybe 1-2%. It could still be nice to ditch the nalgebra dependency... I've basically implemented this on my fork. It needs a bit of polishing, but the matrix stuff is ~200 lines of mostly boilerplate. I'll think about whether I want to open a PR with it.

**Comment by FreezyLemon** [comment]
Even when using const-evaluated LUTs, there doesn't seem to be a noteworthy performance increase. I think it's probably best to "just" ditch the nalgebra dependency by adding some Matrix boilerplate...

**Comment by FreezyLemon** [comment]
@shssoichiro What do you think about publishing a crate like "yuvxyb-matrix" or similar, so we can roll our own matrix math? That shouldn't be too difficult, would allow reuse in ssimulacra2 (we can drop nalgebra there too) and probably allows us to make some functions const later without too much work.

**Comment by shssoichiro** [comment]
If it's reusable, then I think making a new crate for it makes sense.
